# This file was generated by GoReleaser. DO NOT EDIT.
class GolangSeed < Formula
  desc "Golang project starter"
  homepage "https://github.com/dohr-michael/golang-seed"
  url "https://github.com/dohr-michael/golang-seed/releases/download/v0.0.1/golang-seed_0.0.1_Darwin_x86_64.tar.gz"
  version "0.0.1"
  sha256 "316492d63517f8edc254bc2d256a0fff073346f7c4e989e3e186fd0f9811c6c9"

  def install
    bin.install "golang-seed"
  end

  test do
    system "#{bin}/golang-seed version"
  end
end
